//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsForAdmins
    {
        public long id { get; set; }
        public string text { get; set; }
        public Nullable<long> photoId { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public long adminId { get; set; }
        public long userId { get; set; }
        public long typeId { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual RequestForAdminType RequestForAdminType { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Admins { get; set; }
    }
}
