//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonials
    {
        public long id { get; set; }
        public long requestId { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
