//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorLessonLevel
    {
        public long id { get; set; }
        public long tutorId { get; set; }
        public long lessonLevelId { get; set; }
        public int addCost { get; set; }
    
        public virtual LessonLevels LessonLevels { get; set; }
        public virtual Users Users { get; set; }
    }
}
